POST http://localhost:4000/api/integration
Content-Type: application/json

{
  "extOrderId": "bda7-30a02-40e5-bd0b-2bc3c907be4",
  "type": "from", 
  "fromLocation": "Porvoo"
}

###

POST http://localhost:4000/api/integration
Content-Type: application/json

{
  "extOrderId": "bda7-30a02-40e5-bd0b-2bc3c907be4",
  "type": "to", 
  "toLocation": "Kokkola"
}

###

POST http://localhost:4000/api/integration
Content-Type: application/json

{
  "extOrderId": "bda7-30a02-40e5-bd0b-2bc3c907be4",
  "type": "cargo", 
  "cargoType": "Pasta",
  "cargoAmount": 100
}